version: '2'
services:
  bloomRouter:
    image: golang
    command: go run ./cmd/bloomRouter/bloomRouter.go
    volumes:
      - .:/go/src/github.com/vlam321/Inf191BloomFilter
    working_dir: /go/src/github.com/vlam321/Inf191BloomFilter
    ports:
      - "9090:9090"

  bloomServer1:
    image: golang
    environment:
      - SHARD=0
    command: go run ./cmd/bloomFilterServer/bloomFilterServer.go 1000000 10
    volumes:
      - .:/go/src/github.com/vlam321/Inf191BloomFilter
    working_dir: /go/src/github.com/vlam321/Inf191BloomFilter
#    link:
#            - mysql
    ports:
      - "9091:9090"
    
  bloomServer2:
    image: golang
    environment:
      - SHARD=1
    command: go run ./cmd/bloomFilterServer/bloomFilterServer.go 1000000 10
    volumes:
      - .:/go/src/github.com/vlam321/inf191BloomFilter
    working_dir: /go/src/github.com/vlam321/inf191BloomFilter
#    links:
#      - mysql
    ports:
      - "9092:9090"

  bloomServer3:
    image: golang
    environment:
      - SHARD=2
    command: go run ./cmd/bloomFilterServer/bloomFilterServer.go 1000000 10
    volumes:
      - .:/go/src/github.com/vlam321/inf191BloomFilter
    working_dir: /go/src/github.com/vlam321/inf191BloomFilter
#    links:
#      - mysql
    ports:
      - "9093:9090"

#  mysql:
#    hostname: mysql
#    image: percona:5.5
#    environment:
#      - MYSQL_ALLOW_EMPTY_PASSWORD=1
#    ports:
#     - "3306:3306"

