version: '3'

services:
  db:
    image: mysql
    ports: 
      - "3306" #opening port for mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  bloomfilterapp:
    build: .
    depends_on:
      - db #allows bf to connect to db